### ISSUE TITLE
[BUG]: Parameter is set incorrectly (Windows 10 Pro)

### ISSUE THREAD

**Issue by lukyanov** [nezavisimost/FuckRKN1#106] opened 2022-09-10 08:19 UTC
### Description of the bug

Set up everything according to the instructions. Adding the profile goes well. However, when connecting the following error appears: "Parameter is set incorrectly" ("Параметр задан неверно"). I'm trying this in Windows 10 Pro.

### Steps To Reproduce

1. Run the instruction: https://github.com/nezavisimost/FuckRKN1/blob/main/instructions/en/Windows.md
2. Connect.
3. Observe the error.

**Comment by lukyanov** [comment] 2022-09-10 08:26
```
===================================================================
Welcome! Use this helper script to import an IKEv2 configuration
into a PC running Windows 8, 10 or 11.
For more details, see https://vpnsetup.net/ikev2

Before continuing, you must put the .p12 file you transferred from
the VPN server in the *same folder* as this script.
===================================================================

Enter the name of the IKEv2 VPN client to import.
Note: This is the same as the .p12 filename without extension.
To accept the suggested client name, press Enter.
VPN client name: [vpnclient]

Enter the IP address (or DNS name) of the VPN server.
Note: This must exactly match the VPN server address in the output
of the IKEv2 helper script on your server.
VPN server address: lt.fuckrkn1.xyz

Provide a name for the new IKEv2 connection.
To accept the suggested connection name, press Enter.
IKEv2 connection name: [IKEv2 VPN lt.fuckrkn1.xyz]

Importing .p12 file...

Creating VPN connection...


Name                  : IKEv2 VPN lt.fuckrkn1.xyz
ServerAddress         : lt.fuckrkn1.xyz
AllUserConnection     : False
Guid                  : {96566BE8-51B7-4B05-8E7C-9243768DA719}
TunnelType            : Ikev2
AuthenticationMethod  : {MachineCertificate}
EncryptionLevel       : Required
L2tpIPsecAuth         :
UseWinlogonCredential : False
EapConfigXmlStream    :
ConnectionStatus      : Disconnected
RememberCredential    : False
SplitTunneling        : False
DnsSuffix             :
IdleDisconnectSeconds : 0



Setting IPsec configuration...


AuthenticationTransformConstants : GCMAES128
CipherTransformConstants         : GCMAES128
DHGroup                          : Group14
IntegrityCheckMethod             : SHA256
PfsGroup                         : None
EncryptionMethod                 : AES256



IKEv2 configuration successfully imported!
To connect to the VPN, click on the wireless/network icon in your system tray,
select the "IKEv2 VPN lt.fuckrkn1.xyz" VPN entry, and click Connect.

Press any key to exit.
```

**Comment by Schultz68** [comment] 2022-09-14 17:57
I have same problem on Windows 11. I did everything according to the instructions.

**Comment by evgenyKozlov1996** [comment] 2022-09-20 21:09
The same problem on Windows 10 Home. Laptop environment.

**Comment by tr1gl1de** [comment] 2022-09-24 10:50
I have the same problem on Win10 Home, but everything works on IOS.

**Comment by Cotovich** [comment] 2022-09-26 18:44
This helped me on win 11, might be useful to you as well
delete VPN connection before doing instructions
1. run cmd as administrator (find command line in search, click "Run as administrator")
2. run this commands
`netsh int ip reset`
`netsh int ipv6 reset`
`netsh winsock reset`
3. restart computer
4. open Device Manager
5. find Network Adapters
6. uninstall all WAN Miniport drivers (IKEv2, IP, IPv6, etc)
7. click Action > scan for hardware changes
the adapters you just uninstalled should come back
8. set VPN connection

Credit to: [alexmelSC](https://github.com/trailofbits/algo/issues/1051)

**Comment by Schultz68** [comment] 2022-09-26 19:13
Thank You. The problem is solved, everything works.

**Comment by tr1gl1de** [comment] 2022-09-26 19:31
Yep, [it](https://github.com/nezavisimost/FuckRKN1/issues/106#issuecomment-1258458774) really works. Thanks.

**Comment by theyllneverfindyourgrave** [comment] 2022-09-27 15:10
@lukyanov does the @Cotovich 's solution helped you?

**Comment by stransh** [comment] 2022-09-28 05:07
Thanks for the instructions Cotovich! 

The only thing I did is just removed/rescanned wan adapters in devise manager and it worked. So may be try that before going though the all steps you described.

**Comment by theyllneverfindyourgrave** [comment] 2022-09-29 14:38
Most of people solved the problem with [this](https://github.com/nezavisimost/FuckRKN1/issues/106#issuecomment-1258458774) solution, so I am closing the ticket.

**Closed by theyllneverfindyourgrave** 2022-09-29 14:38 UTC
Labels: bug

**Comment by ridebmxrus** [comment] 2023-01-29 04:08
Thank you! God bless you!
[This ](https://github.com/nezavisimost/FuckRKN1/issues/106#issuecomment-1258458774)method helped me to repair Windows 10 22H2 x64 IKEv2 VPN connection

**Comment by sanchez0221** [comment] 2023-01-29 20:46
> This helped me on win 11, might be useful to you as well delete VPN connection before doing instructions
> 
> 1. run cmd as administrator
> 2. run this commands
>    `netsh int ip reset`
>    `netsh int ipv6 reset`
>    `netsh winsock reset`
> 3. restart computer
> 4. open Device Manager
> 5. find Network Adapters
> 6. uninstall all WAN Miniport devices (IKEv2, IP, IPv6, etc)
> 7. click Action > scan for hardware changes
>    the adapters you just uninstalled should come back
> 8. set VPN connection
> 
> Credit to: [alexmelSC](https://github.com/trailofbits/algo/issues/1051)

@Cotovich, thank you a ton, it worked for Windows 10 21H2 x64
